export const bigData = [
    {
        "Type": "Top 2018",
        "name": "God's Plan",
        "artists": "Drake",
        "danceability": "0.754",
        "energy": "0.449",
        "key": "7",
        "loudness": "-9.211",
        "mode": "1",
        "speechiness": "0.109",
        "acousticness": "0.0332",
        "instrumentalness": "8.29E-05",
        "liveness": "0.552",
        "valence": "0.357"
    },
    {
        "Type": "Top 2018",
        "name": "SAD!",
        "artists": "XXXTENTACION",
        "danceability": "0.74",
        "energy": "0.613",
        "key": "8",
        "loudness": "-4.88",
        "mode": "1",
        "speechiness": "0.145",
        "acousticness": "0.258",
        "instrumentalness": "0.00372",
        "liveness": "0.123",
        "valence": "0.473"
    },
    {
        "Type": "Top 2018",
        "name": "rockstar (feat. 21 Savage)",
        "artists": "Post Malone",
        "danceability": "0.587",
        "energy": "0.535",
        "key": "5",
        "loudness": "-6.09",
        "mode": "0",
        "speechiness": "0.0898",
        "acousticness": "0.117",
        "instrumentalness": "6.56E-05",
        "liveness": "0.131",
        "valence": "0.14"
    },
    {
        "Type": "Top 2018",
        "name": "Psycho (feat. Ty Dolla $ign)",
        "artists": "Post Malone",
        "danceability": "0.739",
        "energy": "0.559",
        "key": "8",
        "loudness": "-8.011",
        "mode": "1",
        "speechiness": "0.117",
        "acousticness": "0.58",
        "instrumentalness": "0",
        "liveness": "0.112",
        "valence": "0.439"
    },
    {
        "Type": "Top 2018",
        "name": "In My Feelings",
        "artists": "Drake",
        "danceability": "0.835",
        "energy": "0.626",
        "key": "1",
        "loudness": "-5.833",
        "mode": "1",
        "speechiness": "0.125",
        "acousticness": "0.0589",
        "instrumentalness": "6.00E-05",
        "liveness": "0.396",
        "valence": "0.35"
    },
    {
        "Type": "Top 2018",
        "name": "Better Now",
        "artists": "Post Malone",
        "danceability": "0.68",
        "energy": "0.563",
        "key": "10",
        "loudness": "-5.843",
        "mode": "1",
        "speechiness": "0.0454",
        "acousticness": "0.354",
        "instrumentalness": "0",
        "liveness": "0.136",
        "valence": "0.374"
    },
    {
        "Type": "Top 2018",
        "name": "I Like It",
        "artists": "Cardi B",
        "danceability": "0.816",
        "energy": "0.726",
        "key": "5",
        "loudness": "-3.998",
        "mode": "0",
        "speechiness": "0.129",
        "acousticness": "0.099",
        "instrumentalness": "0",
        "liveness": "0.372",
        "valence": "0.65"
    },
    {
        "Type": "Top 2018",
        "name": "One Kiss (with Dua Lipa)",
        "artists": "Calvin Harris",
        "danceability": "0.791",
        "energy": "0.862",
        "key": "9",
        "loudness": "-3.24",
        "mode": "0",
        "speechiness": "0.11",
        "acousticness": "0.037",
        "instrumentalness": "2.19E-05",
        "liveness": "0.0814",
        "valence": "0.592"
    },
    {
        "Type": "Top 2018",
        "name": "IDGAF",
        "artists": "Dua Lipa",
        "danceability": "0.836",
        "energy": "0.544",
        "key": "7",
        "loudness": "-5.975",
        "mode": "1",
        "speechiness": "0.0943",
        "acousticness": "0.0403",
        "instrumentalness": "0",
        "liveness": "0.0824",
        "valence": "0.51"
    },
    {
        "Type": "Top 2018",
        "name": "FRIENDS",
        "artists": "Marshmello",
        "danceability": "0.626",
        "energy": "0.88",
        "key": "9",
        "loudness": "-2.384",
        "mode": "0",
        "speechiness": "0.0504",
        "acousticness": "0.205",
        "instrumentalness": "0",
        "liveness": "0.128",
        "valence": "0.534"
    },
    {
        "Type": "Top 2018",
        "name": "Havana",
        "artists": "Camila Cabello",
        "danceability": "0.765",
        "energy": "0.523",
        "key": "2",
        "loudness": "-4.333",
        "mode": "1",
        "speechiness": "0.03",
        "acousticness": "0.184",
        "instrumentalness": "3.56E-05",
        "liveness": "0.132",
        "valence": "0.394"
    },
    {
        "Type": "Top 2018",
        "name": "Lucid Dreams",
        "artists": "Juice WRLD",
        "danceability": "0.511",
        "energy": "0.566",
        "key": "6",
        "loudness": "-7.23",
        "mode": "0",
        "speechiness": "0.2",
        "acousticness": "0.349",
        "instrumentalness": "0",
        "liveness": "0.34",
        "valence": "0.218"
    },
    {
        "Type": "Top 2018",
        "name": "Nice For What",
        "artists": "Drake",
        "danceability": "0.586",
        "energy": "0.909",
        "key": "8",
        "loudness": "-6.474",
        "mode": "1",
        "speechiness": "0.0705",
        "acousticness": "0.0891",
        "instrumentalness": "0.000109",
        "liveness": "0.119",
        "valence": "0.757"
    },
    {
        "Type": "Top 2018",
        "name": "Girls Like You (feat. Cardi B)",
        "artists": "Maroon 5",
        "danceability": "0.851",
        "energy": "0.541",
        "key": "0",
        "loudness": "-6.825",
        "mode": "1",
        "speechiness": "0.0505",
        "acousticness": "0.568",
        "instrumentalness": "0",
        "liveness": "0.13",
        "valence": "0.448"
    },
    {
        "Type": "Top 2018",
        "name": "The Middle",
        "artists": "Zedd",
        "danceability": "0.753",
        "energy": "0.657",
        "key": "7",
        "loudness": "-3.061",
        "mode": "1",
        "speechiness": "0.0449",
        "acousticness": "0.171",
        "instrumentalness": "0",
        "liveness": "0.112",
        "valence": "0.437"
    },
    {
        "Type": "Top 2018",
        "name": "All The Stars (with SZA)",
        "artists": "Kendrick Lamar",
        "danceability": "0.698",
        "energy": "0.633",
        "key": "8",
        "loudness": "-4.946",
        "mode": "1",
        "speechiness": "0.0597",
        "acousticness": "0.0605",
        "instrumentalness": "0.000194",
        "liveness": "0.0926",
        "valence": "0.552"
    },
    {
        "Type": "Top 2018",
        "name": "no tears left to cry",
        "artists": "Ariana Grande",
        "danceability": "0.699",
        "energy": "0.713",
        "key": "9",
        "loudness": "-5.507",
        "mode": "0",
        "speechiness": "0.0594",
        "acousticness": "0.04",
        "instrumentalness": "3.11E-06",
        "liveness": "0.294",
        "valence": "0.354"
    },
    {
        "Type": "Top 2018",
        "name": "X",
        "artists": "Nicky Jam",
        "danceability": "0.595",
        "energy": "0.773",
        "key": "9",
        "loudness": "-4.736",
        "mode": "0",
        "speechiness": "0.0549",
        "acousticness": "0.0364",
        "instrumentalness": "0.00108",
        "liveness": "0.334",
        "valence": "0.711"
    },
    {
        "Type": "Top 2018",
        "name": "Moonlight",
        "artists": "XXXTENTACION",
        "danceability": "0.921",
        "energy": "0.537",
        "key": "9",
        "loudness": "-5.723",
        "mode": "0",
        "speechiness": "0.0804",
        "acousticness": "0.556",
        "instrumentalness": "0.00404",
        "liveness": "0.102",
        "valence": "0.711"
    },
    {
        "Type": "Top 2018",
        "name": "Look Alive (feat. Drake)",
        "artists": "BlocBoy JB",
        "danceability": "0.922",
        "energy": "0.581",
        "key": "10",
        "loudness": "-7.495",
        "mode": "1",
        "speechiness": "0.27",
        "acousticness": "0.00104",
        "instrumentalness": "5.86E-05",
        "liveness": "0.105",
        "valence": "0.595"
    },
    {
        "Type": "Top 2018",
        "name": "These Days (feat. Jess Glynne, Macklemore & Dan Caplen)",
        "artists": "Rudimental",
        "danceability": "0.653",
        "energy": "0.809",
        "key": "0",
        "loudness": "-4.057",
        "mode": "1",
        "speechiness": "0.0474",
        "acousticness": "0.194",
        "instrumentalness": "0",
        "liveness": "0.165",
        "valence": "0.55"
    },
    {
        "Type": "Top 2018",
        "name": "Te Bot? - Remix",
        "artists": "Nio Garcia",
        "danceability": "0.903",
        "energy": "0.675",
        "key": "11",
        "loudness": "-3.445",
        "mode": "0",
        "speechiness": "0.214",
        "acousticness": "0.542",
        "instrumentalness": "1.28E-05",
        "liveness": "0.0595",
        "valence": "0.442"
    },
    {
        "Type": "Top 2018",
        "name": "Mine",
        "artists": "Bazzi",
        "danceability": "0.71",
        "energy": "0.789",
        "key": "4",
        "loudness": "-3.874",
        "mode": "1",
        "speechiness": "0.0722",
        "acousticness": "0.0161",
        "instrumentalness": "2.77E-06",
        "liveness": "0.451",
        "valence": "0.717"
    },
    {
        "Type": "Top 2018",
        "name": "Youngblood",
        "artists": "5 Seconds of Summer",
        "danceability": "0.596",
        "energy": "0.854",
        "key": "7",
        "loudness": "-5.114",
        "mode": "0",
        "speechiness": "0.463",
        "acousticness": "0.0169",
        "instrumentalness": "0",
        "liveness": "0.124",
        "valence": "0.152"
    },
    {
        "Type": "Top 2018",
        "name": "New Rules",
        "artists": "Dua Lipa",
        "danceability": "0.762",
        "energy": "0.7",
        "key": "9",
        "loudness": "-6.021",
        "mode": "0",
        "speechiness": "0.0694",
        "acousticness": "0.00261",
        "instrumentalness": "1.56E-05",
        "liveness": "0.153",
        "valence": "0.608"
    },
    {
        "Type": "Top 2018",
        "name": "Shape of You",
        "artists": "Ed Sheeran",
        "danceability": "0.825",
        "energy": "0.652",
        "key": "1",
        "loudness": "-3.183",
        "mode": "0",
        "speechiness": "0.0802",
        "acousticness": "0.581",
        "instrumentalness": "0",
        "liveness": "0.0931",
        "valence": "0.931"
    },
    {
        "Type": "Top 2018",
        "name": "Love Lies (with Normani)",
        "artists": "Khalid",
        "danceability": "0.708",
        "energy": "0.648",
        "key": "6",
        "loudness": "-5.626",
        "mode": "1",
        "speechiness": "0.0449",
        "acousticness": "0.0956",
        "instrumentalness": "0",
        "liveness": "0.134",
        "valence": "0.338"
    },
    {
        "Type": "Top 2018",
        "name": "Meant to Be (feat. Florida Georgia Line)",
        "artists": "Bebe Rexha",
        "danceability": "0.642",
        "energy": "0.772",
        "key": "10",
        "loudness": "-6.61",
        "mode": "1",
        "speechiness": "0.0848",
        "acousticness": "0.0476",
        "instrumentalness": "0",
        "liveness": "0.0646",
        "valence": "0.589"
    },
    {
        "Type": "Top 2018",
        "name": "Jocelyn Flores",
        "artists": "XXXTENTACION",
        "danceability": "0.872",
        "energy": "0.391",
        "key": "0",
        "loudness": "-9.144",
        "mode": "0",
        "speechiness": "0.242",
        "acousticness": "0.469",
        "instrumentalness": "4.13E-06",
        "liveness": "0.297",
        "valence": "0.437"
    },
    {
        "Type": "Top 2018",
        "name": "Perfect",
        "artists": "Ed Sheeran",
        "danceability": "0.599",
        "energy": "0.448",
        "key": "8",
        "loudness": "-6.312",
        "mode": "1",
        "speechiness": "0.0232",
        "acousticness": "0.163",
        "instrumentalness": "0",
        "liveness": "0.106",
        "valence": "0.168"
    },
    {
        "Type": "Top 2018",
        "name": "Taste (feat. Offset)",
        "artists": "Tyga",
        "danceability": "0.884",
        "energy": "0.559",
        "key": "0",
        "loudness": "-7.442",
        "mode": "1",
        "speechiness": "0.12",
        "acousticness": "0.0236",
        "instrumentalness": "0",
        "liveness": "0.101",
        "valence": "0.342"
    },
    {
        "Type": "Top 2018",
        "name": "Solo (feat. Demi Lovato)",
        "artists": "Clean Bandit",
        "danceability": "0.737",
        "energy": "0.636",
        "key": "11",
        "loudness": "-4.546",
        "mode": "0",
        "speechiness": "0.0437",
        "acousticness": "0.0441",
        "instrumentalness": "6.66E-05",
        "liveness": "0.35",
        "valence": "0.565"
    },
    {
        "Type": "Top 2018",
        "name": "I Fall Apart",
        "artists": "Post Malone",
        "danceability": "0.556",
        "energy": "0.538",
        "key": "8",
        "loudness": "-5.408",
        "mode": "0",
        "speechiness": "0.0382",
        "acousticness": "0.0689",
        "instrumentalness": "0",
        "liveness": "0.196",
        "valence": "0.291"
    },
    {
        "Type": "Top 2018",
        "name": "Nevermind",
        "artists": "Dennis Lloyd",
        "danceability": "0.592",
        "energy": "0.691",
        "key": "3",
        "loudness": "-8.354",
        "mode": "1",
        "speechiness": "0.196",
        "acousticness": "0.156",
        "instrumentalness": "9.78E-06",
        "liveness": "0.418",
        "valence": "0.0796"
    },
    {
        "Type": "Top 2018",
        "name": "?chame La Culpa",
        "artists": "Luis Fonsi",
        "danceability": "0.726",
        "energy": "0.889",
        "key": "0",
        "loudness": "-3.655",
        "mode": "1",
        "speechiness": "0.0429",
        "acousticness": "0.0328",
        "instrumentalness": "0",
        "liveness": "0.0925",
        "valence": "0.649"
    },
    {
        "Type": "Top 2018",
        "name": "Eastside (with Halsey & Khalid)",
        "artists": "benny blanco",
        "danceability": "0.56",
        "energy": "0.68",
        "key": "6",
        "loudness": "-7.648",
        "mode": "0",
        "speechiness": "0.321",
        "acousticness": "0.555",
        "instrumentalness": "0",
        "liveness": "0.116",
        "valence": "0.319"
    },
    {
        "Type": "Top 2018",
        "name": "Never Be the Same",
        "artists": "Camila Cabello",
        "danceability": "0.637",
        "energy": "0.713",
        "key": "0",
        "loudness": "-4.333",
        "mode": "1",
        "speechiness": "0.0747",
        "acousticness": "0.181",
        "instrumentalness": "0.000637",
        "liveness": "0.137",
        "valence": "0.243"
    },
    {
        "Type": "Top 2018",
        "name": "Wolves",
        "artists": "Selena Gomez",
        "danceability": "0.72",
        "energy": "0.807",
        "key": "11",
        "loudness": "-4.59",
        "mode": "0",
        "speechiness": "0.0432",
        "acousticness": "0.129",
        "instrumentalness": "0",
        "liveness": "0.183",
        "valence": "0.305"
    },
    {
        "Type": "Top 2018",
        "name": "changes",
        "artists": "XXXTENTACION",
        "danceability": "0.669",
        "energy": "0.308",
        "key": "11",
        "loudness": "-10.068",
        "mode": "1",
        "speechiness": "0.029",
        "acousticness": "0.883",
        "instrumentalness": "0",
        "liveness": "0.0984",
        "valence": "0.52"
    },
    {
        "Type": "Top 2018",
        "name": "In My Mind",
        "artists": "Dynoro",
        "danceability": "0.694",
        "energy": "0.77",
        "key": "6",
        "loudness": "-5.335",
        "mode": "1",
        "speechiness": "0.149",
        "acousticness": "0.176",
        "instrumentalness": "1.10E-05",
        "liveness": "0.118",
        "valence": "0.163"
    },
    {
        "Type": "Top 2018",
        "name": "River (feat. Ed Sheeran)",
        "artists": "Eminem",
        "danceability": "0.748",
        "energy": "0.749",
        "key": "8",
        "loudness": "-5.916",
        "mode": "0",
        "speechiness": "0.516",
        "acousticness": "0.142",
        "instrumentalness": "0",
        "liveness": "0.0713",
        "valence": "0.659"
    },
    {
        "Type": "Top 2018",
        "name": "Dura",
        "artists": "Daddy Yankee",
        "danceability": "0.791",
        "energy": "0.848",
        "key": "1",
        "loudness": "-3.456",
        "mode": "1",
        "speechiness": "0.0506",
        "acousticness": "0.183",
        "instrumentalness": "0",
        "liveness": "0.409",
        "valence": "0.828"
    },
    {
        "Type": "Top 2018",
        "name": "SICKO MODE",
        "artists": "Travis Scott",
        "danceability": "0.834",
        "energy": "0.73",
        "key": "8",
        "loudness": "-3.714",
        "mode": "1",
        "speechiness": "0.222",
        "acousticness": "0.00513",
        "instrumentalness": "0",
        "liveness": "0.124",
        "valence": "0.446"
    },
    {
        "Type": "Top 2018",
        "name": "Thunder",
        "artists": "Imagine Dragons",
        "danceability": "0.605",
        "energy": "0.822",
        "key": "0",
        "loudness": "-4.833",
        "mode": "1",
        "speechiness": "0.0438",
        "acousticness": "0.00671",
        "instrumentalness": "0.134",
        "liveness": "0.147",
        "valence": "0.288"
    },
    {
        "Type": "Top 2018",
        "name": "Me Niego",
        "artists": "Reik",
        "danceability": "0.777",
        "energy": "0.779",
        "key": "0",
        "loudness": "-4.449",
        "mode": "0",
        "speechiness": "0.0972",
        "acousticness": "0.0543",
        "instrumentalness": "0",
        "liveness": "0.636",
        "valence": "0.768"
    },
    {
        "Type": "Top 2018",
        "name": "Jackie Chan",
        "artists": "Ti?sto",
        "danceability": "0.747",
        "energy": "0.834",
        "key": "3",
        "loudness": "-2.867",
        "mode": "0",
        "speechiness": "0.045",
        "acousticness": "0.374",
        "instrumentalness": "0",
        "liveness": "0.0586",
        "valence": "0.687"
    },
    {
        "Type": "Top 2018",
        "name": "Finesse (Remix) [feat. Cardi B]",
        "artists": "Bruno Mars",
        "danceability": "0.704",
        "energy": "0.859",
        "key": "5",
        "loudness": "-4.877",
        "mode": "0",
        "speechiness": "0.0996",
        "acousticness": "0.0185",
        "instrumentalness": "0",
        "liveness": "0.0215",
        "valence": "0.926"
    },
    {
        "Type": "Top 2018",
        "name": "Back To You - From 13 Reasons Why ? Season 2 Soundtrack",
        "artists": "Selena Gomez",
        "danceability": "0.601",
        "energy": "0.724",
        "key": "6",
        "loudness": "-4.856",
        "mode": "1",
        "speechiness": "0.0486",
        "acousticness": "0.0945",
        "instrumentalness": "1.68E-06",
        "liveness": "0.12",
        "valence": "0.508"
    },
    {
        "Type": "Top 2018",
        "name": "Let You Down",
        "artists": "NF",
        "danceability": "0.656",
        "energy": "0.721",
        "key": "5",
        "loudness": "-5.665",
        "mode": "0",
        "speechiness": "0.122",
        "acousticness": "0.298",
        "instrumentalness": "0",
        "liveness": "0.173",
        "valence": "0.468"
    },
    {
        "Type": "Top 2018",
        "name": "Call Out My Name",
        "artists": "The Weeknd",
        "danceability": "0.489",
        "energy": "0.598",
        "key": "1",
        "loudness": "-4.929",
        "mode": "1",
        "speechiness": "0.036",
        "acousticness": "0.218",
        "instrumentalness": "0",
        "liveness": "0.35",
        "valence": "0.172"
    },
    {
        "Type": "Top 2018",
        "name": "Ric Flair Drip (& Metro Boomin)",
        "artists": "Offset",
        "danceability": "0.88",
        "energy": "0.428",
        "key": "9",
        "loudness": "-8.28",
        "mode": "1",
        "speechiness": "0.206",
        "acousticness": "0.149",
        "instrumentalness": "5.07E-05",
        "liveness": "0.114",
        "valence": "0.333"
    },
    {
        "Type": "Top 2018",
        "name": "Happier",
        "artists": "Marshmello",
        "danceability": "0.687",
        "energy": "0.792",
        "key": "5",
        "loudness": "-2.749",
        "mode": "1",
        "speechiness": "0.0452",
        "acousticness": "0.191",
        "instrumentalness": "0",
        "liveness": "0.167",
        "valence": "0.671"
    },
    {
        "Type": "Top 2018",
        "name": "Too Good At Goodbyes",
        "artists": "Sam Smith",
        "danceability": "0.698",
        "energy": "0.375",
        "key": "5",
        "loudness": "-8.279",
        "mode": "1",
        "speechiness": "0.0491",
        "acousticness": "0.652",
        "instrumentalness": "0",
        "liveness": "0.173",
        "valence": "0.534"
    },
    {
        "Type": "Top 2018",
        "name": "Freaky Friday (feat. Chris Brown)",
        "artists": "Lil Dicky",
        "danceability": "0.755",
        "energy": "0.599",
        "key": "8",
        "loudness": "-5.042",
        "mode": "1",
        "speechiness": "0.224",
        "acousticness": "0.147",
        "instrumentalness": "0",
        "liveness": "0.109",
        "valence": "0.755"
    },
    {
        "Type": "Top 2018",
        "name": "Believer",
        "artists": "Imagine Dragons",
        "danceability": "0.776",
        "energy": "0.78",
        "key": "10",
        "loudness": "-4.374",
        "mode": "0",
        "speechiness": "0.128",
        "acousticness": "0.0622",
        "instrumentalness": "0",
        "liveness": "0.081",
        "valence": "0.666"
    },
    {
        "Type": "Top 2018",
        "name": "FEFE (feat. Nicki Minaj & Murda Beatz)",
        "artists": "6ix9ine",
        "danceability": "0.931",
        "energy": "0.387",
        "key": "1",
        "loudness": "-9.127",
        "mode": "1",
        "speechiness": "0.412",
        "acousticness": "0.088",
        "instrumentalness": "0",
        "liveness": "0.136",
        "valence": "0.376"
    },
    {
        "Type": "Top 2018",
        "name": "Rise",
        "artists": "Jonas Blue",
        "danceability": "0.687",
        "energy": "0.785",
        "key": "1",
        "loudness": "-4.65",
        "mode": "1",
        "speechiness": "0.0333",
        "acousticness": "0.327",
        "instrumentalness": "0",
        "liveness": "0.203",
        "valence": "0.655"
    },
    {
        "Type": "Top 2018",
        "name": "Body (feat. brando)",
        "artists": "Loud Luxury",
        "danceability": "0.752",
        "energy": "0.764",
        "key": "1",
        "loudness": "-4.399",
        "mode": "1",
        "speechiness": "0.038",
        "acousticness": "0.0476",
        "instrumentalness": "9.44E-05",
        "liveness": "0.0543",
        "valence": "0.582"
    },
    {
        "Type": "Top 2018",
        "name": "XO TOUR Llif3",
        "artists": "Lil Uzi Vert",
        "danceability": "0.732",
        "energy": "0.75",
        "key": "11",
        "loudness": "-6.366",
        "mode": "0",
        "speechiness": "0.231",
        "acousticness": "0.00264",
        "instrumentalness": "0",
        "liveness": "0.109",
        "valence": "0.401"
    },
    {
        "Type": "Top 2018",
        "name": "Sin Pijama",
        "artists": "Becky G",
        "danceability": "0.791",
        "energy": "0.745",
        "key": "11",
        "loudness": "-3.695",
        "mode": "0",
        "speechiness": "0.0464",
        "acousticness": "0.354",
        "instrumentalness": "2.93E-05",
        "liveness": "0.104",
        "valence": "0.82"
    },
    {
        "Type": "Top 2018",
        "name": "2002",
        "artists": "Anne-Marie",
        "danceability": "0.697",
        "energy": "0.683",
        "key": "1",
        "loudness": "-2.881",
        "mode": "0",
        "speechiness": "0.117",
        "acousticness": "0.0372",
        "instrumentalness": "0",
        "liveness": "0.137",
        "valence": "0.603"
    },
    {
        "Type": "Top 2018",
        "name": "Nonstop",
        "artists": "Drake",
        "danceability": "0.912",
        "energy": "0.412",
        "key": "7",
        "loudness": "-8.074",
        "mode": "1",
        "speechiness": "0.124",
        "acousticness": "0.0164",
        "instrumentalness": "0.013",
        "liveness": "0.104",
        "valence": "0.422"
    },
    {
        "Type": "Top 2018",
        "name": "Fuck Love (feat. Trippie Redd)",
        "artists": "XXXTENTACION",
        "danceability": "0.797",
        "energy": "0.533",
        "key": "0",
        "loudness": "-9.74",
        "mode": "0",
        "speechiness": "0.0412",
        "acousticness": "0.0172",
        "instrumentalness": "0.000152",
        "liveness": "0.103",
        "valence": "0.329"
    },
    {
        "Type": "Top 2018",
        "name": "In My Blood",
        "artists": "Shawn Mendes",
        "danceability": "0.622",
        "energy": "0.712",
        "key": "5",
        "loudness": "-7.321",
        "mode": "1",
        "speechiness": "0.066",
        "acousticness": "0.0573",
        "instrumentalness": "0",
        "liveness": "0.13",
        "valence": "0.487"
    },
    {
        "Type": "Top 2018",
        "name": "Silence",
        "artists": "Marshmello",
        "danceability": "0.52",
        "energy": "0.761",
        "key": "4",
        "loudness": "-3.093",
        "mode": "1",
        "speechiness": "0.0853",
        "acousticness": "0.256",
        "instrumentalness": "4.96E-06",
        "liveness": "0.17",
        "valence": "0.286"
    },
    {
        "Type": "Top 2018",
        "name": "God is a woman",
        "artists": "Ariana Grande",
        "danceability": "0.602",
        "energy": "0.658",
        "key": "1",
        "loudness": "-5.934",
        "mode": "1",
        "speechiness": "0.0558",
        "acousticness": "0.0233",
        "instrumentalness": "6.00E-05",
        "liveness": "0.237",
        "valence": "0.268"
    },
    {
        "Type": "Top 2018",
        "name": "D?jala que vuelva (feat. Manuel Turizo)",
        "artists": "Piso 21",
        "danceability": "0.681",
        "energy": "0.788",
        "key": "1",
        "loudness": "-4.323",
        "mode": "1",
        "speechiness": "0.0785",
        "acousticness": "0.0482",
        "instrumentalness": "0",
        "liveness": "0.0753",
        "valence": "0.839"
    },
    {
        "Type": "Top 2018",
        "name": "Flames",
        "artists": "David Guetta",
        "danceability": "0.631",
        "energy": "0.649",
        "key": "5",
        "loudness": "-5.892",
        "mode": "0",
        "speechiness": "0.0385",
        "acousticness": "0.0817",
        "instrumentalness": "3.80E-06",
        "liveness": "0.0934",
        "valence": "0.421"
    },
    {
        "Type": "Top 2018",
        "name": "What Lovers Do",
        "artists": "Maroon 5",
        "danceability": "0.799",
        "energy": "0.597",
        "key": "5",
        "loudness": "-5.131",
        "mode": "0",
        "speechiness": "0.0611",
        "acousticness": "0.0788",
        "instrumentalness": "5.66E-06",
        "liveness": "0.1",
        "valence": "0.419"
    },
    {
        "Type": "Top 2018",
        "name": "Taki Taki (with Selena Gomez, Ozuna & Cardi B)",
        "artists": "DJ Snake",
        "danceability": "0.841",
        "energy": "0.798",
        "key": "1",
        "loudness": "-4.206",
        "mode": "0",
        "speechiness": "0.229",
        "acousticness": "0.153",
        "instrumentalness": "3.33E-06",
        "liveness": "0.0618",
        "valence": "0.591"
    },
    {
        "Type": "Top 2018",
        "name": "Let Me Go (with Alesso, Florida Georgia Line & watt)",
        "artists": "Hailee Steinfeld",
        "danceability": "0.663",
        "energy": "0.708",
        "key": "8",
        "loudness": "-4.154",
        "mode": "1",
        "speechiness": "0.0473",
        "acousticness": "0.0337",
        "instrumentalness": "0",
        "liveness": "0.0841",
        "valence": "0.742"
    },
    {
        "Type": "Top 2018",
        "name": "Feel It Still",
        "artists": "Portugal. The Man",
        "danceability": "0.801",
        "energy": "0.795",
        "key": "1",
        "loudness": "-5.115",
        "mode": "0",
        "speechiness": "0.0504",
        "acousticness": "0.0417",
        "instrumentalness": "0.000113",
        "liveness": "0.0717",
        "valence": "0.754"
    },
    {
        "Type": "Top 2018",
        "name": "Pray For Me (with Kendrick Lamar)",
        "artists": "The Weeknd",
        "danceability": "0.735",
        "energy": "0.677",
        "key": "2",
        "loudness": "-4.979",
        "mode": "1",
        "speechiness": "0.093",
        "acousticness": "0.0762",
        "instrumentalness": "2.17E-05",
        "liveness": "0.111",
        "valence": "0.188"
    },
    {
        "Type": "Top 2018",
        "name": "Walk It Talk It",
        "artists": "Migos",
        "danceability": "0.909",
        "energy": "0.628",
        "key": "2",
        "loudness": "-5.456",
        "mode": "1",
        "speechiness": "0.201",
        "acousticness": "0.0739",
        "instrumentalness": "0",
        "liveness": "0.108",
        "valence": "0.406"
    },
    {
        "Type": "Top 2018",
        "name": "Him & I (with Halsey)",
        "artists": "G-Eazy",
        "danceability": "0.589",
        "energy": "0.731",
        "key": "2",
        "loudness": "-6.343",
        "mode": "1",
        "speechiness": "0.0868",
        "acousticness": "0.0534",
        "instrumentalness": "0",
        "liveness": "0.308",
        "valence": "0.191"
    },
    {
        "Type": "Top 2018",
        "name": "Candy Paint",
        "artists": "Post Malone",
        "danceability": "0.67",
        "energy": "0.654",
        "key": "4",
        "loudness": "-5.944",
        "mode": "1",
        "speechiness": "0.153",
        "acousticness": "0.627",
        "instrumentalness": "1.02E-06",
        "liveness": "0.071",
        "valence": "0.438"
    },
    {
        "Type": "Top 2018",
        "name": "Congratulations",
        "artists": "Post Malone",
        "danceability": "0.63",
        "energy": "0.804",
        "key": "6",
        "loudness": "-4.183",
        "mode": "1",
        "speechiness": "0.0363",
        "acousticness": "0.215",
        "instrumentalness": "0",
        "liveness": "0.253",
        "valence": "0.492"
    },
    {
        "Type": "Top 2018",
        "name": "1, 2, 3 (feat. Jason Derulo & De La Ghetto)",
        "artists": "Sofia Reyes",
        "danceability": "0.792",
        "energy": "0.895",
        "key": "1",
        "loudness": "-3.112",
        "mode": "0",
        "speechiness": "0.0589",
        "acousticness": "0.165",
        "instrumentalness": "0",
        "liveness": "0.0501",
        "valence": "0.794"
    },
    {
        "Type": "Top 2018",
        "name": "Criminal",
        "artists": "Natti Natasha",
        "danceability": "0.814",
        "energy": "0.813",
        "key": "2",
        "loudness": "-3.023",
        "mode": "0",
        "speechiness": "0.0561",
        "acousticness": "0.03",
        "instrumentalness": "9.33E-05",
        "liveness": "0.255",
        "valence": "0.839"
    },
    {
        "Type": "Top 2018",
        "name": "Plug Walk",
        "artists": "Rich The Kid",
        "danceability": "0.876",
        "energy": "0.519",
        "key": "11",
        "loudness": "-6.531",
        "mode": "1",
        "speechiness": "0.143",
        "acousticness": "0.202",
        "instrumentalness": "0",
        "liveness": "0.108",
        "valence": "0.158"
    },
    {
        "Type": "Top 2018",
        "name": "lovely (with Khalid)",
        "artists": "Billie Eilish",
        "danceability": "0.351",
        "energy": "0.296",
        "key": "4",
        "loudness": "-10.109",
        "mode": "0",
        "speechiness": "0.0333",
        "acousticness": "0.934",
        "instrumentalness": "0",
        "liveness": "0.095",
        "valence": "0.12"
    },
    {
        "Type": "Top 2018",
        "name": "Stir Fry",
        "artists": "Migos",
        "danceability": "0.815",
        "energy": "0.816",
        "key": "2",
        "loudness": "-5.474",
        "mode": "1",
        "speechiness": "0.269",
        "acousticness": "0.00299",
        "instrumentalness": "0",
        "liveness": "0.159",
        "valence": "0.498"
    },
    {
        "Type": "Top 2018",
        "name": "HUMBLE.",
        "artists": "Kendrick Lamar",
        "danceability": "0.908",
        "energy": "0.621",
        "key": "1",
        "loudness": "-6.638",
        "mode": "0",
        "speechiness": "0.102",
        "acousticness": "0.000282",
        "instrumentalness": "5.39E-05",
        "liveness": "0.0958",
        "valence": "0.421"
    },
    {
        "Type": "Top 2018",
        "name": "Vaina Loca",
        "artists": "Ozuna",
        "danceability": "0.754",
        "energy": "0.805",
        "key": "6",
        "loudness": "-4.249",
        "mode": "1",
        "speechiness": "0.0752",
        "acousticness": "0.315",
        "instrumentalness": "0",
        "liveness": "0.203",
        "valence": "0.555"
    },
    {
        "Type": "Top 2018",
        "name": "Perfect Duet (Ed Sheeran & Beyonc?)",
        "artists": "Ed Sheeran",
        "danceability": "0.587",
        "energy": "0.299",
        "key": "8",
        "loudness": "-7.365",
        "mode": "1",
        "speechiness": "0.0263",
        "acousticness": "0.779",
        "instrumentalness": "0",
        "liveness": "0.123",
        "valence": "0.356"
    },
    {
        "Type": "Top 2018",
        "name": "Coraz?n (feat. Nego do Borel)",
        "artists": "Maluma",
        "danceability": "0.722",
        "energy": "0.738",
        "key": "9",
        "loudness": "-6.073",
        "mode": "0",
        "speechiness": "0.247",
        "acousticness": "0.328",
        "instrumentalness": "1.47E-05",
        "liveness": "0.198",
        "valence": "0.748"
    },
    {
        "Type": "Top 2018",
        "name": "Young Dumb & Broke",
        "artists": "Khalid",
        "danceability": "0.798",
        "energy": "0.539",
        "key": "1",
        "loudness": "-6.351",
        "mode": "1",
        "speechiness": "0.0421",
        "acousticness": "0.199",
        "instrumentalness": "1.66E-05",
        "liveness": "0.165",
        "valence": "0.394"
    },
    {
        "Type": "Top 2018",
        "name": "S?guelo Bailando",
        "artists": "Ozuna",
        "danceability": "0.855",
        "energy": "0.664",
        "key": "9",
        "loudness": "-7.11",
        "mode": "0",
        "speechiness": "0.0607",
        "acousticness": "0.165",
        "instrumentalness": "3.97E-05",
        "liveness": "0.0937",
        "valence": "0.626"
    },
    {
        "Type": "Top 2018",
        "name": "Downtown",
        "artists": "Anitta",
        "danceability": "0.775",
        "energy": "0.679",
        "key": "4",
        "loudness": "-4.985",
        "mode": "0",
        "speechiness": "0.135",
        "acousticness": "0.18",
        "instrumentalness": "7.26E-05",
        "liveness": "0.068",
        "valence": "0.619"
    },
    {
        "Type": "Top 2018",
        "name": "Bella",
        "artists": "Wolfine",
        "danceability": "0.909",
        "energy": "0.493",
        "key": "3",
        "loudness": "-6.688",
        "mode": "1",
        "speechiness": "0.0735",
        "acousticness": "0.128",
        "instrumentalness": "0.000147",
        "liveness": "0.127",
        "valence": "0.844"
    },
    {
        "Type": "Top 2018",
        "name": "Promises (with Sam Smith)",
        "artists": "Calvin Harris",
        "danceability": "0.781",
        "energy": "0.768",
        "key": "11",
        "loudness": "-5.991",
        "mode": "1",
        "speechiness": "0.0394",
        "acousticness": "0.0119",
        "instrumentalness": "4.91E-06",
        "liveness": "0.325",
        "valence": "0.486"
    },
    {
        "Type": "Top 2018",
        "name": "Yes Indeed",
        "artists": "Lil Baby",
        "danceability": "0.964",
        "energy": "0.346",
        "key": "5",
        "loudness": "-9.309",
        "mode": "0",
        "speechiness": "0.53",
        "acousticness": "0.035",
        "instrumentalness": "0",
        "liveness": "0.108",
        "valence": "0.562"
    },
    {
        "Type": "Top 2018",
        "name": "I Like Me Better",
        "artists": "Lauv",
        "danceability": "0.752",
        "energy": "0.505",
        "key": "9",
        "loudness": "-7.621",
        "mode": "1",
        "speechiness": "0.253",
        "acousticness": "0.535",
        "instrumentalness": "2.55E-06",
        "liveness": "0.104",
        "valence": "0.419"
    },
    {
        "Type": "Top 2018",
        "name": "This Is Me",
        "artists": "Keala Settle",
        "danceability": "0.284",
        "energy": "0.704",
        "key": "2",
        "loudness": "-7.276",
        "mode": "1",
        "speechiness": "0.186",
        "acousticness": "0.00583",
        "instrumentalness": "0.000115",
        "liveness": "0.0424",
        "valence": "0.1"
    },
    {
        "Type": "Top 2018",
        "name": "Everybody Dies In Their Nightmares",
        "artists": "XXXTENTACION",
        "danceability": "0.734",
        "energy": "0.57",
        "key": "7",
        "loudness": "-7.066",
        "mode": "0",
        "speechiness": "0.133",
        "acousticness": "0.847",
        "instrumentalness": "2.14E-05",
        "liveness": "0.112",
        "valence": "0.689"
    },
    {
        "Type": "Top 2018",
        "name": "Rewrite The Stars",
        "artists": "Zac Efron",
        "danceability": "0.684",
        "energy": "0.619",
        "key": "10",
        "loudness": "-7.005",
        "mode": "1",
        "speechiness": "0.0386",
        "acousticness": "0.0716",
        "instrumentalness": "0",
        "liveness": "0.122",
        "valence": "0.284"
    },
    {
        "Type": "Top 2018",
        "name": "I Miss You (feat. Julia Michaels)",
        "artists": "Clean Bandit",
        "danceability": "0.638",
        "energy": "0.658",
        "key": "3",
        "loudness": "-6.318",
        "mode": "1",
        "speechiness": "0.0456",
        "acousticness": "0.245",
        "instrumentalness": "3.77E-06",
        "liveness": "0.0919",
        "valence": "0.33"
    },
    {
        "Type": "Top 2018",
        "name": "No Brainer",
        "artists": "DJ Khaled",
        "danceability": "0.552",
        "energy": "0.76",
        "key": "0",
        "loudness": "-4.706",
        "mode": "1",
        "speechiness": "0.342",
        "acousticness": "0.0733",
        "instrumentalness": "0",
        "liveness": "0.0865",
        "valence": "0.639"
    },
    {
        "Type": "Top 2018",
        "name": "Dusk Till Dawn - Radio Edit",
        "artists": "ZAYN",
        "danceability": "0.258",
        "energy": "0.437",
        "key": "11",
        "loudness": "-6.593",
        "mode": "0",
        "speechiness": "0.039",
        "acousticness": "0.101",
        "instrumentalness": "1.27E-06",
        "liveness": "0.106",
        "valence": "0.0967"
    },
    {
        "Type": "Top 2018",
        "name": "Be Alright",
        "artists": "Dean Lewis",
        "danceability": "0.553",
        "energy": "0.586",
        "key": "11",
        "loudness": "-6.319",
        "mode": "1",
        "speechiness": "0.0362",
        "acousticness": "0.697",
        "instrumentalness": "0",
        "liveness": "0.0813",
        "valence": "0.443"
    },
    {
        "Type": "Mary's Music",
        "name": "Breakfast in Bed",
        "artists": "Sugar Candy Mountain",
        "danceability": "0.654",
        "energy": "0.717",
        "key": "1",
        "loudness": "-7.515",
        "mode": "0",
        "speechiness": "0.0658",
        "acousticness": "0.196",
        "instrumentalness": "0.00109",
        "liveness": "0.342",
        "valence": "0.731"
    },
    {
        "Type": "Mary's Music",
        "name": "No. 28",
        "artists": "Methyl Ethel",
        "danceability": "0.558",
        "energy": "0.696",
        "key": "2",
        "loudness": "-5.52",
        "mode": "1",
        "speechiness": "0.027",
        "acousticness": "0.00588",
        "instrumentalness": "0.0295",
        "liveness": "0.0988",
        "valence": "0.527"
    },
    {
        "Type": "Mary's Music",
        "name": "Casimir Pulaski Day",
        "artists": "Sufjan Stevens",
        "danceability": "0.686",
        "energy": "0.172",
        "key": "8",
        "loudness": "-14.979",
        "mode": "1",
        "speechiness": "0.0409",
        "acousticness": "0.909",
        "instrumentalness": "0.00154",
        "liveness": "0.286",
        "valence": "0.563"
    },
    {
        "Type": "Mary's Music",
        "name": "PS2",
        "artists": "Litany",
        "danceability": "0.818",
        "energy": "0.326",
        "key": "9",
        "loudness": "-9.705",
        "mode": "1",
        "speechiness": "0.0387",
        "acousticness": "0.093",
        "instrumentalness": "0.0218",
        "liveness": "0.261",
        "valence": "0.531"
    },
    {
        "Type": "Mary's Music",
        "name": "Yes I'm Changing",
        "artists": "Tame Impala",
        "danceability": "0.373",
        "energy": "0.609",
        "key": "0",
        "loudness": "-7",
        "mode": "1",
        "speechiness": "0.0316",
        "acousticness": "0.108",
        "instrumentalness": "0.000427",
        "liveness": "0.0755",
        "valence": "0.354"
    },
    {
        "Type": "Mary's Music",
        "name": "Slow Down - 12\" Version",
        "artists": "Bobby V.",
        "danceability": "0.563",
        "energy": "0.746",
        "key": "11",
        "loudness": "-4.832",
        "mode": "0",
        "speechiness": "0.101",
        "acousticness": "0.17",
        "instrumentalness": "5.58E-06",
        "liveness": "0.338",
        "valence": "0.598"
    },
    {
        "Type": "Mary's Music",
        "name": "The Start Of Something",
        "artists": "Voxtrot",
        "danceability": "0.632",
        "energy": "0.733",
        "key": "8",
        "loudness": "-6.924",
        "mode": "1",
        "speechiness": "0.0293",
        "acousticness": "0.179",
        "instrumentalness": "1.04E-05",
        "liveness": "0.0988",
        "valence": "0.707"
    },
    {
        "Type": "Mary's Music",
        "name": "Set Piece",
        "artists": "Vansire",
        "danceability": "0.541",
        "energy": "0.483",
        "key": "1",
        "loudness": "-10.675",
        "mode": "0",
        "speechiness": "0.0514",
        "acousticness": "0.351",
        "instrumentalness": "0.4",
        "liveness": "0.111",
        "valence": "0.641"
    },
    {
        "Type": "Mary's Music",
        "name": "Remind Me to Forget",
        "artists": "Kygo",
        "danceability": "0.685",
        "energy": "0.508",
        "key": "0",
        "loudness": "-6.4",
        "mode": "1",
        "speechiness": "0.0987",
        "acousticness": "0.193",
        "instrumentalness": "0",
        "liveness": "0.139",
        "valence": "0.315"
    },
    {
        "Type": "Mary's Music",
        "name": "When You Were Mine",
        "artists": "Prince",
        "danceability": "0.694",
        "energy": "0.444",
        "key": "9",
        "loudness": "-13.254",
        "mode": "1",
        "speechiness": "0.0648",
        "acousticness": "0.00657",
        "instrumentalness": "0.776",
        "liveness": "0.0719",
        "valence": "0.879"
    },
    {
        "Type": "Mary's Music",
        "name": "Sunflower - Spider-Man: Into the Spider-Verse",
        "artists": "Post Malone",
        "danceability": "0.753",
        "energy": "0.498",
        "key": "2",
        "loudness": "-5.61",
        "mode": "1",
        "speechiness": "0.0504",
        "acousticness": "0.551",
        "instrumentalness": "0",
        "liveness": "0.0706",
        "valence": "0.927"
    },
    {
        "Type": "Mary's Music",
        "name": "Saturday Nights",
        "artists": "Khalid",
        "danceability": "0.54",
        "energy": "0.439",
        "key": "10",
        "loudness": "-8.591",
        "mode": "1",
        "speechiness": "0.115",
        "acousticness": "0.635",
        "instrumentalness": "1.93E-05",
        "liveness": "0.0993",
        "valence": "0.371"
    },
    {
        "Type": "Mary's Music",
        "name": "Lula Loves You",
        "artists": "Farao",
        "danceability": "0.509",
        "energy": "0.548",
        "key": "10",
        "loudness": "-11.212",
        "mode": "0",
        "speechiness": "0.0844",
        "acousticness": "0.000326",
        "instrumentalness": "3.01E-05",
        "liveness": "0.413",
        "valence": "0.479"
    },
    {
        "Type": "Mary's Music",
        "name": "Too Fast",
        "artists": "Sonder",
        "danceability": "0.395",
        "energy": "0.33",
        "key": "4",
        "loudness": "-10.924",
        "mode": "0",
        "speechiness": "0.0408",
        "acousticness": "0.316",
        "instrumentalness": "1.89E-05",
        "liveness": "0.268",
        "valence": "0.102"
    },
    {
        "Type": "Mary's Music",
        "name": "BLEACH",
        "artists": "BROCKHAMPTON",
        "danceability": "0.595",
        "energy": "0.657",
        "key": "1",
        "loudness": "-6.498",
        "mode": "0",
        "speechiness": "0.183",
        "acousticness": "0.462",
        "instrumentalness": "0.000597",
        "liveness": "0.437",
        "valence": "0.718"
    },
    {
        "Type": "Mary's Music",
        "name": "Gap in the Clouds",
        "artists": "Yellow Days",
        "danceability": "0.576",
        "energy": "0.535",
        "key": "9",
        "loudness": "-8.392",
        "mode": "1",
        "speechiness": "0.041",
        "acousticness": "0.588",
        "instrumentalness": "0.0106",
        "liveness": "0.31",
        "valence": "0.196"
    },
    {
        "Type": "Mary's Music",
        "name": "It's Alright",
        "artists": "Horsebeach",
        "danceability": "0.584",
        "energy": "0.621",
        "key": "11",
        "loudness": "-9.863",
        "mode": "1",
        "speechiness": "0.0251",
        "acousticness": "0.0221",
        "instrumentalness": "0.0753",
        "liveness": "0.113",
        "valence": "0.694"
    },
    {
        "Type": "Mary's Music",
        "name": "Total Zombie",
        "artists": "Day Wave",
        "danceability": "0.563",
        "energy": "0.842",
        "key": "4",
        "loudness": "-8.011",
        "mode": "1",
        "speechiness": "0.0284",
        "acousticness": "0.325",
        "instrumentalness": "0.293",
        "liveness": "0.157",
        "valence": "0.729"
    },
    {
        "Type": "Mary's Music",
        "name": "Cool with You",
        "artists": "Her's",
        "danceability": "0.533",
        "energy": "0.613",
        "key": "0",
        "loudness": "-6.773",
        "mode": "1",
        "speechiness": "0.0495",
        "acousticness": "0.0124",
        "instrumentalness": "0.000684",
        "liveness": "0.299",
        "valence": "0.554"
    },
    {
        "Type": "Mary's Music",
        "name": "SICKO MODE",
        "artists": "Travis Scott",
        "danceability": "0.834",
        "energy": "0.73",
        "key": "8",
        "loudness": "-3.714",
        "mode": "1",
        "speechiness": "0.222",
        "acousticness": "0.00513",
        "instrumentalness": "0",
        "liveness": "0.124",
        "valence": "0.446"
    },
    {
        "Type": "Mary's Music",
        "name": "Chinatown",
        "artists": "Wild Nothing",
        "danceability": "0.59",
        "energy": "0.501",
        "key": "5",
        "loudness": "-11.895",
        "mode": "0",
        "speechiness": "0.0319",
        "acousticness": "0.00155",
        "instrumentalness": "0.154",
        "liveness": "0.0916",
        "valence": "0.317"
    },
    {
        "Type": "Mary's Music",
        "name": "This / That",
        "artists": "Sarah Jaffe",
        "danceability": "0.728",
        "energy": "0.506",
        "key": "6",
        "loudness": "-10.199",
        "mode": "1",
        "speechiness": "0.0365",
        "acousticness": "0.0891",
        "instrumentalness": "0.0109",
        "liveness": "0.11",
        "valence": "0.349"
    },
    {
        "Type": "Mary's Music",
        "name": "We Find Love",
        "artists": "Daniel Caesar",
        "danceability": "0.51",
        "energy": "0.363",
        "key": "5",
        "loudness": "-8.635",
        "mode": "1",
        "speechiness": "0.0304",
        "acousticness": "0.853",
        "instrumentalness": "0",
        "liveness": "0.109",
        "valence": "0.426"
    },
    {
        "Type": "Mary's Music",
        "name": "Saturdays (feat. HAIM)",
        "artists": "Twin Shadow",
        "danceability": "0.47",
        "energy": "0.696",
        "key": "9",
        "loudness": "-4.749",
        "mode": "1",
        "speechiness": "0.104",
        "acousticness": "0.0659",
        "instrumentalness": "3.85E-05",
        "liveness": "0.0962",
        "valence": "0.802"
    },
    {
        "Type": "Mary's Music",
        "name": "Chasing Waves",
        "artists": "Vista Kicks",
        "danceability": "0.379",
        "energy": "0.781",
        "key": "8",
        "loudness": "-5.756",
        "mode": "1",
        "speechiness": "0.0738",
        "acousticness": "0.316",
        "instrumentalness": "0.0052",
        "liveness": "0.13",
        "valence": "0.422"
    },
    {
        "Type": "Mary's Music",
        "name": "Drugs",
        "artists": "M.A.G.S.",
        "danceability": "0.577",
        "energy": "0.845",
        "key": "10",
        "loudness": "-7.606",
        "mode": "0",
        "speechiness": "0.0351",
        "acousticness": "0.0355",
        "instrumentalness": "2.77E-05",
        "liveness": "0.0814",
        "valence": "0.692"
    },
    {
        "Type": "Mary's Music",
        "name": "Lil Thing",
        "artists": "Knox Fortune",
        "danceability": "0.689",
        "energy": "0.803",
        "key": "7",
        "loudness": "-3.929",
        "mode": "1",
        "speechiness": "0.15",
        "acousticness": "0.23",
        "instrumentalness": "1.95E-05",
        "liveness": "0.0897",
        "valence": "0.659"
    },
    {
        "Type": "Mary's Music",
        "name": "Because I‚Äôm Me",
        "artists": "The Avalanches",
        "danceability": "0.472",
        "energy": "0.805",
        "key": "8",
        "loudness": "-5.793",
        "mode": "1",
        "speechiness": "0.086",
        "acousticness": "0.0491",
        "instrumentalness": "0.0162",
        "liveness": "0.337",
        "valence": "0.512"
    },
    {
        "Type": "Mary's Music",
        "name": "I Need A Woman",
        "artists": "Hockey Dad",
        "danceability": "0.344",
        "energy": "0.935",
        "key": "1",
        "loudness": "-5.204",
        "mode": "1",
        "speechiness": "0.0756",
        "acousticness": "0.00538",
        "instrumentalness": "0",
        "liveness": "0.233",
        "valence": "0.296"
    },
    {
        "Type": "Mary's Music",
        "name": "Close To You",
        "artists": "Rihanna",
        "danceability": "0.494",
        "energy": "0.17",
        "key": "10",
        "loudness": "-11.368",
        "mode": "1",
        "speechiness": "0.0337",
        "acousticness": "0.895",
        "instrumentalness": "0",
        "liveness": "0.139",
        "valence": "0.145"
    },
    {
        "Type": "Mary's Music",
        "name": "Our Park By Night",
        "artists": "Craft Spells",
        "danceability": "0.551",
        "energy": "0.761",
        "key": "7",
        "loudness": "-7",
        "mode": "1",
        "speechiness": "0.0303",
        "acousticness": "0.277",
        "instrumentalness": "0.00771",
        "liveness": "0.289",
        "valence": "0.739"
    },
    {
        "Type": "Mary's Music",
        "name": "Living Single",
        "artists": "Big Sean",
        "danceability": "0.717",
        "energy": "0.618",
        "key": "11",
        "loudness": "-5.419",
        "mode": "1",
        "speechiness": "0.315",
        "acousticness": "0.214",
        "instrumentalness": "0",
        "liveness": "0.108",
        "valence": "0.719"
    },
    {
        "Type": "Mary's Music",
        "name": "Four Out Of Five",
        "artists": "Arctic Monkeys",
        "danceability": "0.601",
        "energy": "0.863",
        "key": "0",
        "loudness": "-4.31",
        "mode": "1",
        "speechiness": "0.0685",
        "acousticness": "0.0626",
        "instrumentalness": "0",
        "liveness": "0.0717",
        "valence": "0.676"
    },
    {
        "Type": "Mary's Music",
        "name": "The Light",
        "artists": "Jeremih",
        "danceability": "0.83",
        "energy": "0.577",
        "key": "4",
        "loudness": "-5.156",
        "mode": "0",
        "speechiness": "0.256",
        "acousticness": "0.0178",
        "instrumentalness": "8.15E-05",
        "liveness": "0.0436",
        "valence": "0.63"
    },
    {
        "Type": "Mary's Music",
        "name": "deep end",
        "artists": "Lykke Li",
        "danceability": "0.538",
        "energy": "0.586",
        "key": "11",
        "loudness": "-6.937",
        "mode": "0",
        "speechiness": "0.0482",
        "acousticness": "0.288",
        "instrumentalness": "1.73E-06",
        "liveness": "0.116",
        "valence": "0.381"
    },
    {
        "Type": "Mary's Music",
        "name": "Sister Golden Hair",
        "artists": "America",
        "danceability": "0.441",
        "energy": "0.547",
        "key": "4",
        "loudness": "-12.222",
        "mode": "1",
        "speechiness": "0.0337",
        "acousticness": "0.13",
        "instrumentalness": "0.000143",
        "liveness": "0.109",
        "valence": "0.716"
    },
    {
        "Type": "Mary's Music",
        "name": "Impressions of You",
        "artists": "The Virgins",
        "danceability": "0.692",
        "energy": "0.547",
        "key": "9",
        "loudness": "-6.564",
        "mode": "1",
        "speechiness": "0.0269",
        "acousticness": "0.145",
        "instrumentalness": "0.00154",
        "liveness": "0.131",
        "valence": "0.482"
    },
    {
        "Type": "Mary's Music",
        "name": "I. Flight Of The Navigator",
        "artists": "Childish Gambino",
        "danceability": "0.443",
        "energy": "0.686",
        "key": "6",
        "loudness": "-9.744",
        "mode": "0",
        "speechiness": "0.0389",
        "acousticness": "0.0614",
        "instrumentalness": "0.126",
        "liveness": "0.118",
        "valence": "0.149"
    },
    {
        "Type": "Mary's Music",
        "name": "This Is America",
        "artists": "Childish Gambino",
        "danceability": "0.854",
        "energy": "0.463",
        "key": "5",
        "loudness": "-6.159",
        "mode": "1",
        "speechiness": "0.137",
        "acousticness": "0.117",
        "instrumentalness": "0",
        "liveness": "0.354",
        "valence": "0.549"
    },
    {
        "Type": "Mary's Music",
        "name": "Get You (feat. Kali Uchis)",
        "artists": "Daniel Caesar",
        "danceability": "0.658",
        "energy": "0.294",
        "key": "4",
        "loudness": "-8.533",
        "mode": "0",
        "speechiness": "0.0321",
        "acousticness": "0.422",
        "instrumentalness": "5.20E-05",
        "liveness": "0.0749",
        "valence": "0.358"
    },
    {
        "Type": "Mary's Music",
        "name": "Saint Ivy",
        "artists": "Beach Fossils",
        "danceability": "0.39",
        "energy": "0.546",
        "key": "11",
        "loudness": "-6.588",
        "mode": "0",
        "speechiness": "0.0346",
        "acousticness": "0.0338",
        "instrumentalness": "0.0586",
        "liveness": "0.328",
        "valence": "0.441"
    },
    {
        "Type": "Mary's Music",
        "name": "One Last Time",
        "artists": "Summer Salt",
        "danceability": "0.71",
        "energy": "0.359",
        "key": "1",
        "loudness": "-10.925",
        "mode": "1",
        "speechiness": "0.0281",
        "acousticness": "0.754",
        "instrumentalness": "0.228",
        "liveness": "0.0894",
        "valence": "0.434"
    },
    {
        "Type": "Mary's Music",
        "name": "Living Safe",
        "artists": "Makeup Girl",
        "danceability": "0.413",
        "energy": "0.659",
        "key": "5",
        "loudness": "-9.115",
        "mode": "1",
        "speechiness": "0.0408",
        "acousticness": "0.0128",
        "instrumentalness": "4.25E-06",
        "liveness": "0.12",
        "valence": "0.346"
    },
    {
        "Type": "Mary's Music",
        "name": "After The Storm (feat. Tyler, The Creator & Bootsy Collins)",
        "artists": "Kali Uchis",
        "danceability": "0.734",
        "energy": "0.657",
        "key": "4",
        "loudness": "-6.625",
        "mode": "0",
        "speechiness": "0.128",
        "acousticness": "0.304",
        "instrumentalness": "0.000785",
        "liveness": "0.247",
        "valence": "0.814"
    },
    {
        "Type": "Mary's Music",
        "name": "Best Tears",
        "artists": "The Happy Fits",
        "danceability": "0.415",
        "energy": "0.702",
        "key": "2",
        "loudness": "-3.73",
        "mode": "1",
        "speechiness": "0.04",
        "acousticness": "0.109",
        "instrumentalness": "0",
        "liveness": "0.119",
        "valence": "0.68"
    },
    {
        "Type": "Mary's Music",
        "name": "Nice For What",
        "artists": "Drake",
        "danceability": "0.567",
        "energy": "0.913",
        "key": "8",
        "loudness": "-6.471",
        "mode": "1",
        "speechiness": "0.0736",
        "acousticness": "0.0934",
        "instrumentalness": "0.000124",
        "liveness": "0.114",
        "valence": "0.792"
    },
    {
        "Type": "Mary's Music",
        "name": "Alaska",
        "artists": "Maggie Rogers",
        "danceability": "0.837",
        "energy": "0.312",
        "key": "0",
        "loudness": "-13.797",
        "mode": "1",
        "speechiness": "0.0702",
        "acousticness": "0.313",
        "instrumentalness": "0.0175",
        "liveness": "0.0923",
        "valence": "0.145"
    },
    {
        "Type": "Mary's Music",
        "name": "Moon Child",
        "artists": "The F16s",
        "danceability": "0.606",
        "energy": "0.713",
        "key": "9",
        "loudness": "-5.987",
        "mode": "1",
        "speechiness": "0.0314",
        "acousticness": "0.0568",
        "instrumentalness": "0.00262",
        "liveness": "0.0814",
        "valence": "0.549"
    },
    {
        "Type": "Mary's Music",
        "name": "Moon River",
        "artists": "Frank Ocean",
        "danceability": "0.24",
        "energy": "0.116",
        "key": "0",
        "loudness": "-13.216",
        "mode": "1",
        "speechiness": "0.0329",
        "acousticness": "0.877",
        "instrumentalness": "0.00092",
        "liveness": "0.1",
        "valence": "0.0937"
    },
    {
        "Type": "Mary's Music",
        "name": "Obvs",
        "artists": "Jamie xx",
        "danceability": "0.649",
        "energy": "0.392",
        "key": "5",
        "loudness": "-12.603",
        "mode": "0",
        "speechiness": "0.0375",
        "acousticness": "0.856",
        "instrumentalness": "0.926",
        "liveness": "0.0817",
        "valence": "0.415"
    },
    {
        "Type": "Mary's Music",
        "name": "Australia",
        "artists": "The Shins",
        "danceability": "0.434",
        "energy": "0.842",
        "key": "4",
        "loudness": "-4.468",
        "mode": "1",
        "speechiness": "0.038",
        "acousticness": "0.00442",
        "instrumentalness": "0.000142",
        "liveness": "0.308",
        "valence": "0.838"
    },
    {
        "Type": "Mary's Music",
        "name": "In the Morning I'll Be Better",
        "artists": "Tennis",
        "danceability": "0.343",
        "energy": "0.607",
        "key": "0",
        "loudness": "-5.048",
        "mode": "1",
        "speechiness": "0.0357",
        "acousticness": "0.632",
        "instrumentalness": "0.00808",
        "liveness": "0.0824",
        "valence": "0.599"
    },
    {
        "Type": "Mary's Music",
        "name": "Pantyhose",
        "artists": "TV Girl",
        "danceability": "0.522",
        "energy": "0.847",
        "key": "7",
        "loudness": "-4.444",
        "mode": "1",
        "speechiness": "0.0395",
        "acousticness": "0.505",
        "instrumentalness": "0.0015",
        "liveness": "0.217",
        "valence": "0.757"
    },
    {
        "Type": "Mary's Music",
        "name": "Hold Me Down",
        "artists": "Daniel Caesar",
        "danceability": "0.463",
        "energy": "0.427",
        "key": "8",
        "loudness": "-9.799",
        "mode": "0",
        "speechiness": "0.0549",
        "acousticness": "0.628",
        "instrumentalness": "0.000565",
        "liveness": "0.0911",
        "valence": "0.231"
    },
    {
        "Type": "Mary's Music",
        "name": "Talk",
        "artists": "Henry Hall",
        "danceability": "0.674",
        "energy": "0.345",
        "key": "10",
        "loudness": "-10.904",
        "mode": "1",
        "speechiness": "0.0506",
        "acousticness": "0.587",
        "instrumentalness": "0.000132",
        "liveness": "0.137",
        "valence": "0.267"
    },
    {
        "Type": "Mary's Music",
        "name": "Warm (feat. Mia)",
        "artists": "Dre'es",
        "danceability": "0.662",
        "energy": "0.297",
        "key": "8",
        "loudness": "-14.525",
        "mode": "1",
        "speechiness": "0.0301",
        "acousticness": "0.888",
        "instrumentalness": "0.108",
        "liveness": "0.119",
        "valence": "0.434"
    },
    {
        "Type": "Mary's Music",
        "name": "Best Friend",
        "artists": "Rex Orange County",
        "danceability": "0.575",
        "energy": "0.714",
        "key": "6",
        "loudness": "-5.247",
        "mode": "1",
        "speechiness": "0.0596",
        "acousticness": "0.395",
        "instrumentalness": "0",
        "liveness": "0.115",
        "valence": "0.32"
    },
    {
        "Type": "Mary's Music",
        "name": "Operator (He Doesn't Call Me)",
        "artists": "L√•psley",
        "danceability": "0.734",
        "energy": "0.596",
        "key": "2",
        "loudness": "-7.529",
        "mode": "1",
        "speechiness": "0.0407",
        "acousticness": "0.0931",
        "instrumentalness": "0.000777",
        "liveness": "0.308",
        "valence": "0.311"
    },
    {
        "Type": "Mary's Music",
        "name": "Stream",
        "artists": "Last Dinosaurs",
        "danceability": "0.452",
        "energy": "0.886",
        "key": "0",
        "loudness": "-5.524",
        "mode": "1",
        "speechiness": "0.0856",
        "acousticness": "0.00026",
        "instrumentalness": "0",
        "liveness": "0.0944",
        "valence": "0.681"
    },
    {
        "Type": "Mary's Music",
        "name": "Sunny",
        "artists": "Bobby Hebb",
        "danceability": "0.711",
        "energy": "0.347",
        "key": "4",
        "loudness": "-10.955",
        "mode": "0",
        "speechiness": "0.0394",
        "acousticness": "0.93",
        "instrumentalness": "0.0134",
        "liveness": "0.403",
        "valence": "0.661"
    },
    {
        "Type": "Mary's Music",
        "name": "D√≠melo",
        "artists": "Snakehips",
        "danceability": "0.566",
        "energy": "0.444",
        "key": "7",
        "loudness": "-12.069",
        "mode": "0",
        "speechiness": "0.147",
        "acousticness": "0.0522",
        "instrumentalness": "0",
        "liveness": "0.158",
        "valence": "0.161"
    },
    {
        "Type": "Mary's Music",
        "name": "What Once Was",
        "artists": "Her's",
        "danceability": "0.522",
        "energy": "0.875",
        "key": "3",
        "loudness": "-4.375",
        "mode": "0",
        "speechiness": "0.0323",
        "acousticness": "0.177",
        "instrumentalness": "0.0101",
        "liveness": "0.212",
        "valence": "0.472"
    },
    {
        "Type": "Mary's Music",
        "name": "Twilight",
        "artists": "Elliott Smith",
        "danceability": "0.428",
        "energy": "0.377",
        "key": "0",
        "loudness": "-13.039",
        "mode": "1",
        "speechiness": "0.0351",
        "acousticness": "0.269",
        "instrumentalness": "0.00223",
        "liveness": "0.183",
        "valence": "0.487"
    },
    {
        "Type": "Mary's Music",
        "name": "Marcel",
        "artists": "Her's",
        "danceability": "0.624",
        "energy": "0.65",
        "key": "9",
        "loudness": "-5.993",
        "mode": "1",
        "speechiness": "0.0277",
        "acousticness": "0.529",
        "instrumentalness": "0.0748",
        "liveness": "0.334",
        "valence": "0.655"
    },
    {
        "Type": "Mary's Music",
        "name": "Two Weeks",
        "artists": "Grizzly Bear",
        "danceability": "0.537",
        "energy": "0.712",
        "key": "5",
        "loudness": "-5.597",
        "mode": "1",
        "speechiness": "0.0286",
        "acousticness": "0.289",
        "instrumentalness": "0.00568",
        "liveness": "0.08",
        "valence": "0.704"
    },
    {
        "Type": "Mary's Music",
        "name": "That Feeling",
        "artists": "Dent May",
        "danceability": "0.538",
        "energy": "0.693",
        "key": "0",
        "loudness": "-5.947",
        "mode": "1",
        "speechiness": "0.0309",
        "acousticness": "0.372",
        "instrumentalness": "0",
        "liveness": "0.336",
        "valence": "0.412"
    },
    {
        "Type": "Mary's Music",
        "name": "Birds Dont Sing",
        "artists": "TV Girl",
        "danceability": "0.612",
        "energy": "0.942",
        "key": "7",
        "loudness": "-4.549",
        "mode": "1",
        "speechiness": "0.0568",
        "acousticness": "0.016",
        "instrumentalness": "0",
        "liveness": "0.137",
        "valence": "0.807"
    },
    {
        "Type": "Mary's Music",
        "name": "You've Got a Woman",
        "artists": "Whitney",
        "danceability": "0.49",
        "energy": "0.83",
        "key": "10",
        "loudness": "-5.178",
        "mode": "0",
        "speechiness": "0.0366",
        "acousticness": "0.197",
        "instrumentalness": "9.41E-05",
        "liveness": "0.349",
        "valence": "0.763"
    }
];